//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Story_Test10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrdID { get; set; }
        public string OrdGuid { get; set; }
        public string MemID { get; set; }
        public string Receiver { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public System.DateTime OrdDate { get; set; }
        public Nullable<decimal> OrdAmount { get; set; }
        public Nullable<int> OrdTotal { get; set; }
        public string Transport { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual OrderMapping OrderMapping { get; set; }
    }
}
