//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryTest3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Announcement
    {
        [DisplayName("公告編號")]

        public string PostID { get; set; }

        [DisplayName("管理員編號")]

        public string AdminID { get; set; }

        [DisplayName("公告名稱")]
        [Required(ErrorMessage = "請輸入公告名稱")]

        public string PostName { get; set; }

        [DisplayName("公告時間")]
        [Required(ErrorMessage = "請輸入正確的格式：年/月/日")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public System.DateTime PostTime { get; set; }

        [DisplayName("公告內文")]
        [Required(ErrorMessage = "請輸入內文")]

        public string PostCont { get; set; }


        public virtual Administrator Administrator { get; set; }
    }
}
