//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryTest3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageMapping
    {
        public string MessageID { get; set; }
        public string MemID { get; set; }
        public string ReplyID { get; set; }
        public string MessageCont { get; set; }
        public System.DateTime MessageTime { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual MessageReply MessageReply { get; set; }
    }
}
