//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04EntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


    public partial class student
    {
        [DisplayName("學號")]
        [Required(ErrorMessage ="學號為必填")]
        [RegularExpression("[1-9]{1}[0-9]{2}[0-9]{3}",ErrorMessage ="學號格式有誤")]  //標準表達式
        public string fStuId { get; set; }
        [DisplayName("姓名")]
        [Required(ErrorMessage = "姓名為必填")]
        public string fName { get; set; }
        [DisplayName("信箱")]
        [EmailAddress(ErrorMessage = "信箱格式有誤")]
        public string fEmail { get; set; }
        [DisplayName("成績")]
        [Range(0,100,ErrorMessage ="成績請填0~100的整數")]
        public Nullable<int> fScore { get; set; }
    }
}
