//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Story_Test8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMapping
    {
        public string OrdID { get; set; }
        public string MemID { get; set; }
        public string CommID { get; set; }
        public string IndustryID { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string CommName { get; set; }
        public Nullable<decimal> OrdAmount { get; set; }
        public Nullable<int> OrdTotal { get; set; }
        public string IsApproved { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Total { get; set; }
    
        public virtual Commodity Commodity { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual Member Member { get; set; }
        public virtual Order Order { get; set; }
    }
}
