//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Story_Test7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionLog
    {
        public long ActionLogSN { get; set; }
        public System.DateTime logTime { get; set; }
        public string controllerName { get; set; }
        public string actionName { get; set; }
        public string parame { get; set; }
    }
}
