//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Story_Test7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommodityReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommodityReport()
        {
            this.CommodityReportMapping = new HashSet<CommodityReportMapping>();
        }
    
        public string CommRepID { get; set; }
        public string CommID { get; set; }
        public string CommRepFactor { get; set; }
        public System.DateTime CommRepDate { get; set; }
    
        public virtual Commodity Commodity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommodityReportMapping> CommodityReportMapping { get; set; }
    }
}
